name: Solidify Training Demo

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  reusable: SolidifyDemo/actions-training-031122/.github/workflows/reusable-build.yml@main
