name: Solidify Training Demo

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  reusable:
    uses: actions-training-031122/reusable-build.yml@main
