name: Action training demo

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  UseReusable:
    uses: SolidifyDemo/reusable-workflows/.github/dotnet-reusable-ci.yml@main
